### ISSUE TITLE
Tag (versioning) request

### ISSUE THREAD

**Issue by patkar** [texane/stlink#145]
I don't know how stable the master is, so it would be cool if you could provide (more or less) stable releases as tags.

**Comment by xor-gate** [comment]
Things are moving forward, people are contributing, testing and fixing. We will now stick to semver as mentioned by @patkar because this is what most software libraries and tools use and is well documented and understand. I have updated the README accordingly. FYI i'm cleaning up things to bump a major release `v2.0.0` milestone because there will be a change in commandline argument parsing and library interfaces (click on the milestone icon to see what is going on): https://github.com/texane/stlink/milestones/v2.0.0

Thanks for the discussion all.
