### ISSUE TITLE
flashing: Cannot flash while usb on stm32f4discovery is in use

### ISSUE THREAD

**Issue by SietseAchterop** [texane/stlink#160]
```
Dear list,
```

When my discovery board is loaded with a program that uses the usb of the stm32f4,
the output of  " st-flash write  stm32f4_usb_cdc.bin 0x08000000"  is:
   2013-06-13T08:16:52 WARN src/stlink-usb.c: Couldn't open ST-Link/V2 device 008:037
With only the debug usb-interface it works perfectly.

lsusb:
      ....
   Bus 004 Device 028: ID 0483:3748 SGS Thomson Microelectronics ST-LINK/V2
   Bus 008 Device 037: ID 0483:5740 SGS Thomson Microelectronics 

Is the st-link software confused by the 2 STM devices?
    Regards, Sietse

**Comment by Nightwalker-87** [comment]
No clear why this was closed, may deserve further investigation, if the code can do something about it.

**Comment by Nightwalker-87** [comment]
@SietseAchterop @cstratton @dimanlin: Which versions of the st-link toolset did you use? Please provide more details on your setups and build environments and describe the problem more precisely.

**Comment by Nightwalker-87** [comment]
This seems to be a hardware-related issue on some STM32F4 Discovery boards, which prevents correct programmer detection. On the other hand it appears reasonable that an USB interface can't be used for programming and application-related tasks at the same time. Likely this requires the application to be interrupted by an appropriate signal in order to put the board in a state which enables the integrated programmer to fully claim the USB port.
