### ISSUE TITLE
Custom continuous integration with Jenkins

### ISSUE THREAD

**Issue by xor-gate** [texane/stlink#461]
We can continue discussion in this issue from PR #444.

**Comment by nekromant** [comment]
@xor-gate FYI: I've set up a branch pipeline test with a sample Jenkinsfile here:

http://github.com/nekromant/stlink (see pipeline-test)
And a relevant project in ci
https://jenkins.ncrmnt.org/job/GithubCI/job/stlink-branch-ci/

It's not yet working, I'll be playing with DSL  when I have a spare minute. 

It looks like scan-build you've been missing there was because of this bug: 
https://issues.jenkins-ci.org/browse/JENKINS-29872

Should be trivial to fix in scan-build plugin if they haven't done already.

**Comment by xor-gate** [comment]
IMHO you may just remove the pipeline build. If we need this in the future we could always figure out something. Thank you for your time @nekromant !

**Comment by Nightwalker-87** [comment]
Is there still any demand for this feature request?

**Comment by Nightwalker-87** [comment]
Travis CI is being used for continuous integration since Apr 2016 (commit ca08bed617efc86a7765554c14a448b731f97eb3).
Since no further demand has been registered for this feature, this ticket is now finally closed.
