### ISSUE TITLE
[NUCLEO] stm32l053r8 - unknown chip id! 0x10086417

### ISSUE THREAD

**Issue by OBU5** [texane/stlink#626]
Hello guys. 

I have Problem with uploading binary to Board

I have Nucleo board stm32l053r8, and I am able to upload there binary with STSW-LINK004.
But It is for Windows and I am programming on Linux. When I was uploading binary to Discovery board, there was no Problem, but now, when I wrote in bash "st-flash erase" or , bash told me "unknown chip id! 0x10086417"
(like in the first picture)
![obrazek](https://user-images.githubusercontent.com/30869245/29126782-94b57254-7d1f-11e7-9841-3f059d4a00b6.png)

When I write it with my discovery board (STM32 F0308DISCOVERY), everything seems alright.
(like in the second picture)
![obrazek](https://user-images.githubusercontent.com/30869245/29126388-89f13d86-7d1e-11e7-8a08-2f8e062fdd5c.png)

dont you know, where should be a problem? :( ...

Please help me :( I am lost

src/stlink-common.c: unknown chip id! 0x10086417

**Comment by xor-gate** [comment]
Please provide the requested information (as per [ISSUE_TEMPLATE.md](https://github.com/texane/stlink/blob/master/.github/ISSUE_TEMPLATE.md)) about which st-util you are using. Probably your version is to old. Since v1.2.0 L053 is supported (see [ChangeLog.md](https://github.com/texane/stlink/blob/master/ChangeLog.md#v120))

**Comment by OBU5** [comment]
Thank you for your reply.

Yeah I realy had a old version. Thank you very much !!!!! :)

**Comment by xor-gate** [comment]
Great, thank you for your reply.
